import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Products from '../components/Product'
import Banner from '../components/Banner'
import styles from '../styles/Home.module.css'
import Categories from '../components/Categories'
import { getAllProduct } from '../../api/product'
import { getAllCategory } from '../../api/category'
import { ICategory } from '../models/category'
import { IProduct } from '../models/product'
import { ISlide } from '../models/slide'
import { getAllSlide } from '../../api/slide'
type HomeProps = {
  listSliders: ISlide[];
  listProducts: IProduct[];
  listCategory: ICategory[];
};
const Home = ({listCategory,listProducts,listSliders}: HomeProps) => {
  return (
    <div>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Banner listSliders={listSliders}/>
    <Categories listCategory={listCategory} />
    <Products listProducts={listProducts}/>
    </div>
        </div>
  )
}
export const getStaticProps: GetStaticProps = async () => {
  const listSliders = await getAllSlide();
  const listProducts = await getAllProduct();
  const listCategory = await getAllCategory();

  // if (!sliders || !products || !listCategory || !newsList) {
  //   return {
  //     notFound: true,
  //   };
  // }

  return {
    props: {
      listSliders,
      listProducts,
      listCategory,
    },
    revalidate: 60,
  };
};
export default Home
