import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Products from '../components/Product'
import Banner from '../components/Banner'
import styles from '../styles/Home.module.css'
import Categories from '../components/Categories'

const Home: NextPage = () => {
  return (
    <div>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Banner/>
    <Categories />
    <Products/>
    </div>
        </div>
  )
}

export default Home
